import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { CheckCircle, AlertTriangle, XCircle, Shield, Baby, Tag, Sparkles, Search, Youtube, ExternalLink, Copy, Download, Check } from "lucide-react";
import type { VideoAnalysis, AlternativeSuggestion } from "@shared/schema";
import { cn } from "@/lib/utils";
import { useToast } from "@/hooks/use-toast";

interface AnalysisModalProps {
  isOpen: boolean;
  onClose: () => void;
  analysis: VideoAnalysis | null;
  onSearchAlternative?: (query: string) => void;
}

export function AnalysisModal({ isOpen, onClose, analysis, onSearchAlternative }: AnalysisModalProps) {
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();
  
  if (!analysis) {
    return null;
  }

  const isSafe = analysis.isAppropriate;
  const confidence = analysis.confidenceScore || 0;
  const alternatives = analysis.alternativeSuggestions as AlternativeSuggestion[] | null;
  
  const StatusIcon = isSafe ? CheckCircle : XCircle;

  const generateReportText = () => {
    const safetyStatus = isSafe ? "SAFE" : "NOT RECOMMENDED";
    const tags = analysis.tags?.join(", ") || "None detected";
    
    let report = `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
KIDSSAFE TUBE - SAFETY REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

VIDEO TITLE:
${analysis.title}

SAFETY RATING: ${safetyStatus}
CONFIDENCE: ${confidence}%
AGE RECOMMENDATION: ${analysis.ageRating || "Not Rated"}

DETECTED THEMES: ${tags}

EXPLANATION:
${analysis.reasoning || "No explanation available."}
`;

    if (!isSafe && alternatives && alternatives.length > 0) {
      report += `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RECOMMENDED ALTERNATIVES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;
      alternatives.forEach((alt, i) => {
        report += `
${i + 1}. ${alt.reason}
   Search: "${alt.searchQuery}"
   Channels: ${alt.suggestedChannels?.join(", ") || "N/A"}
`;
      });
    }

    report += `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by KidsSafe Tube
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`;

    return report;
  };

  const handleCopyReport = async () => {
    try {
      if (!navigator.clipboard) {
        throw new Error("Clipboard not supported");
      }
      await navigator.clipboard.writeText(generateReportText());
      setCopied(true);
      toast({
        title: "Report copied!",
        description: "The safety report has been copied to your clipboard.",
      });
      const timeoutId = setTimeout(() => setCopied(false), 2000);
      return () => clearTimeout(timeoutId);
    } catch (err) {
      toast({
        title: "Failed to copy",
        description: "Please try again or use the download option.",
        variant: "destructive",
      });
    }
  };

  const handleDownloadReport = () => {
    try {
      const report = generateReportText();
      const blob = new Blob([report], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `safety-report-${analysis.youtubeId}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      toast({
        title: "Report downloaded!",
        description: "The safety report has been saved to your device.",
      });
    } catch (err) {
      toast({
        title: "Download failed",
        description: "Unable to download the report. Please try copying instead.",
        variant: "destructive",
      });
    }
  };

  const handleSearchAlternative = (query: string) => {
    if (onSearchAlternative) {
      onSearchAlternative(query);
      onClose();
    }
  };

  const openYouTubeChannel = (channelName: string) => {
    const searchUrl = `https://www.youtube.com/results?search_query=${encodeURIComponent(channelName)}`;
    window.open(searchUrl, "_blank");
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent 
        className="w-full max-w-2xl max-h-[95vh] sm:max-h-[90vh] overflow-y-auto overflow-x-hidden border-0 p-0 rounded-t-3xl sm:rounded-3xl fixed bottom-0 sm:bottom-auto sm:top-1/2 sm:-translate-y-1/2 left-0 right-0 sm:left-1/2 sm:-translate-x-1/2 mx-auto"
        data-testid="modal-analysis"
      >
        <DialogHeader className="sr-only">
          <DialogTitle>Safety Analysis Report</DialogTitle>
          <DialogDescription>
            {isSafe ? "This content appears safe for children" : "This content may not be appropriate for children"}
          </DialogDescription>
        </DialogHeader>
        {/* Header Section with Dynamic Color */}
        <div className={cn(
          "px-4 sm:px-6 py-6 sm:py-8 relative overflow-hidden",
          isSafe ? "bg-gradient-to-br from-green-500 to-emerald-600" : "bg-gradient-to-br from-red-500 to-rose-600"
        )}>
          {/* Background Pattern */}
          <div className="absolute inset-0 opacity-10 bg-[radial-gradient(circle_at_1px_1px,#fff_1px,transparent_0)] bg-[length:20px_20px]" />
          
          <div className="relative z-10 text-white">
            <div className="flex items-center gap-2 sm:gap-3 mb-3 sm:mb-4 flex-wrap">
              <Badge className="bg-white/20 hover:bg-white/30 text-white border-0 backdrop-blur-sm px-2 sm:px-3 py-1 text-xs sm:text-sm">
                Safety Report
              </Badge>
              <Badge 
                className="bg-white/20 hover:bg-white/30 text-white border-0 backdrop-blur-sm px-2 sm:px-3 py-1 text-xs sm:text-sm"
                data-testid="badge-confidence"
              >
                {confidence}% Confidence
              </Badge>
            </div>
            
            <h2 
              className="text-xl sm:text-3xl font-display font-bold mb-2 flex items-center gap-2 sm:gap-3 flex-wrap"
              data-testid="text-safety-status"
            >
              {isSafe ? "Content Appears Safe" : "Content May Be Unsafe"}
              <div className="bg-white/20 p-1.5 sm:p-2 rounded-full backdrop-blur-sm">
                <StatusIcon className="w-5 h-5 sm:w-8 sm:h-8" />
              </div>
            </h2>
            <p className="text-white/90 text-sm sm:text-lg line-clamp-2" data-testid="text-video-title">
              {analysis.title}
            </p>
            
            {/* Export Buttons */}
            <div className="flex items-center gap-2 mt-3 sm:mt-4">
              <Button
                size="sm"
                variant="secondary"
                onClick={handleCopyReport}
                className="bg-white/20 hover:bg-white/30 text-white border-0 backdrop-blur-sm gap-1.5 sm:gap-2 text-xs sm:text-sm min-h-[44px] sm:min-h-[36px] px-3 sm:px-3"
                data-testid="button-copy-report"
              >
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copied ? "Copied!" : "Copy"}
              </Button>
              <Button
                size="sm"
                variant="secondary"
                onClick={handleDownloadReport}
                className="bg-white/20 hover:bg-white/30 text-white border-0 backdrop-blur-sm gap-1.5 sm:gap-2 text-xs sm:text-sm min-h-[44px] sm:min-h-[36px] px-3 sm:px-3"
                data-testid="button-download-report"
              >
                <Download className="w-4 h-4" />
                Download
              </Button>
            </div>
          </div>
        </div>

        {/* Content Section */}
        <div className="p-4 sm:p-6 bg-background space-y-4 sm:space-y-6">
          {/* Reasoning Card */}
          <div className="bg-card border rounded-xl sm:rounded-2xl p-4 sm:p-5 shadow-sm">
            <h3 className="text-xs sm:text-sm font-semibold uppercase tracking-wider text-muted-foreground mb-2 sm:mb-3 flex items-center gap-2">
              <Shield className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
              Safety Reasoning
            </h3>
            <p className="text-sm sm:text-base text-foreground leading-relaxed" data-testid="text-reasoning">
              {analysis.reasoning}
            </p>
          </div>

          <div className="grid grid-cols-2 gap-3 sm:gap-4">
            {/* Age Rating */}
            <div className="bg-secondary/30 rounded-xl sm:rounded-2xl p-3 sm:p-4 border border-secondary/50">
              <h4 className="text-xs sm:text-sm font-semibold text-muted-foreground mb-1 sm:mb-2 flex items-center gap-1.5 sm:gap-2">
                <Baby className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
                Age Rating
              </h4>
              <div className="text-lg sm:text-2xl font-display font-bold text-foreground" data-testid="text-age-rating">
                {analysis.ageRating || "Not Rated"}
              </div>
            </div>

            {/* Tags */}
            <div className="bg-secondary/30 rounded-xl sm:rounded-2xl p-3 sm:p-4 border border-secondary/50">
              <h4 className="text-xs sm:text-sm font-semibold text-muted-foreground mb-1 sm:mb-2 flex items-center gap-1.5 sm:gap-2">
                <Tag className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
                Themes
              </h4>
              <div className="flex flex-wrap gap-1 sm:gap-2" data-testid="container-tags">
                {analysis.tags?.slice(0, 4).map((tag, i) => (
                  <Badge key={i} variant="outline" className="bg-white dark:bg-secondary text-xs" data-testid={`badge-tag-${i}`}>
                    {tag}
                  </Badge>
                )) || <span className="text-xs sm:text-sm text-muted-foreground">None</span>}
                {analysis.tags && analysis.tags.length > 4 && (
                  <Badge variant="outline" className="bg-white dark:bg-secondary text-xs">
                    +{analysis.tags.length - 4}
                  </Badge>
                )}
              </div>
            </div>
          </div>

          {/* Alternative Suggestions Section - Only shown when content is unsafe */}
          {!isSafe && alternatives && alternatives.length > 0 && (
            <div 
              className="bg-gradient-to-br from-primary/5 to-accent/5 border border-primary/20 rounded-xl sm:rounded-2xl p-4 sm:p-5"
              data-testid="container-alternatives"
            >
              <h3 className="text-base sm:text-lg font-display font-bold text-foreground mb-3 sm:mb-4 flex items-center gap-2">
                <Sparkles className="w-4 h-4 sm:w-5 sm:h-5 text-primary" />
                Kid-Friendly Alternatives
              </h3>
              <p className="text-xs sm:text-sm text-muted-foreground mb-3 sm:mb-4">
                Here are some safe alternatives for children:
              </p>
              
              <div className="space-y-3 sm:space-y-4">
                {alternatives.map((alt, index) => (
                  <div 
                    key={index} 
                    className="bg-card rounded-xl p-3 sm:p-4 border shadow-sm"
                    data-testid={`card-alternative-${index}`}
                  >
                    <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-2 sm:gap-4 mb-2 sm:mb-3">
                      <div className="flex-1">
                        <p className="text-xs sm:text-sm text-muted-foreground mb-1">{alt.reason}</p>
                        <p className="text-sm sm:text-base font-semibold text-foreground flex items-center gap-2">
                          <Search className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-primary flex-shrink-0" />
                          <span className="truncate">"{alt.searchQuery}"</span>
                        </p>
                      </div>
                      {onSearchAlternative && (
                        <Button 
                          size="sm" 
                          onClick={() => handleSearchAlternative(alt.searchQuery)}
                          className="w-full sm:w-auto min-h-[44px] sm:min-h-[36px]"
                          data-testid={`button-search-alternative-${index}`}
                        >
                          <Search className="w-4 h-4 mr-1.5 sm:hidden" />
                          Search This
                        </Button>
                      )}
                    </div>
                    
                    {alt.suggestedChannels && alt.suggestedChannels.length > 0 && (
                      <div>
                        <p className="text-xs text-muted-foreground mb-1.5 sm:mb-2 flex items-center gap-1">
                          <Youtube className="w-3 h-3" />
                          Kid-friendly channels:
                        </p>
                        <div className="flex flex-wrap gap-1.5 sm:gap-2">
                          {alt.suggestedChannels.map((channel, channelIndex) => (
                            <Badge 
                              key={channelIndex} 
                              variant="secondary"
                              className="cursor-pointer hover-elevate gap-1.5 text-xs active:scale-95 min-h-[36px] sm:min-h-[28px] px-2.5 py-1.5"
                              onClick={() => openYouTubeChannel(channel)}
                              data-testid={`badge-channel-${index}-${channelIndex}`}
                            >
                              {channel}
                              <ExternalLink className="w-3 h-3" />
                            </Badge>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
