import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { CheckCircle, XCircle, Shield, Zap, Info, Download, Copy, Check, AlertTriangle, RefreshCw } from "lucide-react";
import type { ChannelAnalysis, ChannelVideoBreakdown } from "@shared/schema";
import { cn } from "@/lib/utils";
import { useToast } from "@/hooks/use-toast";

interface ChannelAnalysisModalProps {
  isOpen: boolean;
  onClose: () => void;
  analysis: ChannelAnalysis | null;
  onReanalyze?: (channelId: string) => void;
  isReanalyzing?: boolean;
}

const gradeColors: Record<string, { bg: string; text: string; gradient: string }> = {
  A: { bg: "bg-green-500", text: "text-green-700 dark:text-green-400", gradient: "from-green-500 to-emerald-600" },
  B: { bg: "bg-blue-500", text: "text-blue-700 dark:text-blue-400", gradient: "from-blue-500 to-cyan-600" },
  C: { bg: "bg-amber-500", text: "text-amber-700 dark:text-amber-400", gradient: "from-amber-500 to-yellow-600" },
  D: { bg: "bg-orange-500", text: "text-orange-700 dark:text-orange-400", gradient: "from-orange-500 to-red-500" },
  F: { bg: "bg-red-500", text: "text-red-700 dark:text-red-400", gradient: "from-red-500 to-rose-600" },
};

const getOverstimColor = (rating: string) => {
  switch (rating) {
    case "low": return { bg: "bg-green-100 dark:bg-green-900/30", text: "text-green-700 dark:text-green-400", border: "border-green-200 dark:border-green-800" };
    case "moderate": return { bg: "bg-amber-100 dark:bg-amber-900/30", text: "text-amber-700 dark:text-amber-400", border: "border-amber-200 dark:border-amber-800" };
    case "high": return { bg: "bg-red-100 dark:bg-red-900/30", text: "text-red-700 dark:text-red-400", border: "border-red-200 dark:border-red-800" };
    default: return { bg: "bg-secondary", text: "text-muted-foreground", border: "border-secondary" };
  }
};

export function ChannelAnalysisModal({ isOpen, onClose, analysis, onReanalyze, isReanalyzing }: ChannelAnalysisModalProps) {
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  if (!analysis) return null;

  const grade = analysis.overallGrade || "C";
  const gradeStyle = gradeColors[grade] || gradeColors.C;
  const breakdown = analysis.videoBreakdown as ChannelVideoBreakdown[] | null;
  const concerns = analysis.topConcerns as string[] | null;
  const overstimRating = analysis.overstimulationRating || "moderate";
  const overstimStyle = getOverstimColor(overstimRating);
  const isSafe = grade === "A" || grade === "B";

  const generateReportText = () => {
    let report = `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SafeStream - CHANNEL SAFETY REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CHANNEL: ${analysis.channelName}
OVERALL GRADE: ${grade}
VIDEOS ANALYZED: ${analysis.totalAnalyzed}
SAFE: ${analysis.safeCount} | FLAGGED: ${analysis.flaggedCount}

OVERSTIMULATION LEVEL: ${overstimRating.toUpperCase()}

SUMMARY:
${analysis.overallReasoning}
`;

    if (concerns && concerns.length > 0) {
      report += `
TOP CONCERNS:
${concerns.map((c, i) => `${i + 1}. ${c}`).join("\n")}
`;
    }

    if (breakdown && breakdown.length > 0) {
      report += `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
VIDEO BREAKDOWN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;
      breakdown.forEach((v, i) => {
        report += `
${i + 1}. "${v.title}"
   Safety: ${v.isAppropriate ? "Safe" : "Flagged"} | Age: ${v.ageRating} | Confidence: ${v.confidenceScore}% | Overstim: ${v.overstimulationRating}
`;
      });
    }

    report += `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
WHITELIST RECOMMENDATION: ${isSafe ? "SAFE TO WHITELIST" : "NOT RECOMMENDED FOR WHITELISTING"}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by SafeStream
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`;
    return report;
  };

  const handleCopyReport = async () => {
    try {
      if (!navigator.clipboard) throw new Error("Clipboard not supported");
      await navigator.clipboard.writeText(generateReportText());
      setCopied(true);
      toast({ title: "Report copied!", description: "The channel safety report has been copied to your clipboard." });
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast({ title: "Failed to copy", description: "Please try again or use the download option.", variant: "destructive" });
    }
  };

  const handleDownloadReport = () => {
    try {
      const report = generateReportText();
      const blob = new Blob([report], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `channel-report-${analysis.channelId}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast({ title: "Report downloaded!", description: "The channel report has been saved to your device." });
    } catch {
      toast({ title: "Download failed", description: "Unable to download the report.", variant: "destructive" });
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent
        className="w-full max-w-2xl max-h-[95vh] sm:max-h-[90vh] overflow-y-auto overflow-x-hidden border-0 p-0 rounded-t-3xl sm:rounded-3xl fixed bottom-0 sm:bottom-auto sm:top-1/2 sm:-translate-y-1/2 left-0 right-0 sm:left-1/2 sm:-translate-x-1/2 mx-auto"
        data-testid="modal-channel-analysis"
      >
        <DialogHeader className="sr-only">
          <DialogTitle>Channel Safety Report</DialogTitle>
          <DialogDescription>
            {isSafe ? "This channel appears safe for children" : "This channel may contain content not suitable for children"}
          </DialogDescription>
        </DialogHeader>

        <div className={cn("px-4 sm:px-6 py-6 sm:py-8 relative overflow-hidden bg-gradient-to-br", gradeStyle.gradient)}>
          <div className="absolute inset-0 opacity-10 bg-[radial-gradient(circle_at_1px_1px,#fff_1px,transparent_0)] bg-[length:20px_20px]" />

          <div className="relative z-10 text-white">
            <div className="flex items-center gap-2 sm:gap-3 mb-3 sm:mb-4 flex-wrap">
              <Badge className="bg-white/20 hover:bg-white/30 text-white border-0 backdrop-blur-sm px-2 sm:px-3 py-1 text-xs sm:text-sm">
                Channel Report
              </Badge>
              <Badge className="bg-white/20 hover:bg-white/30 text-white border-0 backdrop-blur-sm px-2 sm:px-3 py-1 text-xs sm:text-sm" data-testid="badge-videos-analyzed">
                {analysis.totalAnalyzed} videos analyzed
              </Badge>
            </div>

            <div className="flex items-center gap-4 mb-2">
              <div className="w-16 h-16 sm:w-20 sm:h-20 bg-white/20 backdrop-blur-sm rounded-2xl flex items-center justify-center" data-testid="badge-channel-grade">
                <span className="text-3xl sm:text-4xl font-display font-black">{grade}</span>
              </div>
              <div className="flex-1">
                <h2 className="text-xl sm:text-3xl font-display font-bold mb-1" data-testid="text-channel-name">
                  {analysis.channelName}
                </h2>
                <p className="text-white/80 text-sm sm:text-base">
                  {isSafe ? "Safe to whitelist" : "Not recommended for whitelisting"}
                </p>
              </div>
            </div>

            <div className="flex items-center gap-2 mt-3 sm:mt-4">
              <Button size="sm" variant="secondary" onClick={handleCopyReport}
                className="bg-white/20 hover:bg-white/30 text-white border-0 backdrop-blur-sm gap-1.5 text-xs sm:text-sm min-h-[44px] sm:min-h-[36px] px-3"
                data-testid="button-copy-channel-report">
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copied ? "Copied!" : "Copy"}
              </Button>
              <Button size="sm" variant="secondary" onClick={handleDownloadReport}
                className="bg-white/20 hover:bg-white/30 text-white border-0 backdrop-blur-sm gap-1.5 text-xs sm:text-sm min-h-[44px] sm:min-h-[36px] px-3"
                data-testid="button-download-channel-report">
                <Download className="w-4 h-4" />
                Download
              </Button>
              {onReanalyze && (
                <Button size="sm" variant="secondary"
                  onClick={() => onReanalyze(analysis.channelId)}
                  disabled={isReanalyzing}
                  className="bg-white/20 hover:bg-white/30 text-white border-0 backdrop-blur-sm gap-1.5 text-xs sm:text-sm min-h-[44px] sm:min-h-[36px] px-3"
                  data-testid="button-reanalyze-channel">
                  <RefreshCw className={cn("w-4 h-4", isReanalyzing && "animate-spin")} />
                  {isReanalyzing ? "Re-analyzing..." : "Re-analyze"}
                </Button>
              )}
            </div>
          </div>
        </div>

        <div className="p-4 sm:p-6 bg-background space-y-4 sm:space-y-6">
          <div className="bg-card border rounded-xl sm:rounded-2xl p-4 sm:p-5 shadow-sm">
            <h3 className="text-xs sm:text-sm font-semibold uppercase tracking-wider text-muted-foreground mb-2 sm:mb-3 flex items-center gap-2">
              <Shield className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
              Overall Assessment
            </h3>
            <p className="text-sm sm:text-base text-foreground leading-relaxed" data-testid="text-channel-reasoning">
              {analysis.overallReasoning}
            </p>
          </div>

          <div className="grid grid-cols-3 gap-3 sm:gap-4">
            <div className="bg-green-50 dark:bg-green-900/20 rounded-xl sm:rounded-2xl p-3 sm:p-4 border border-green-200 dark:border-green-800 text-center">
              <div className="text-2xl sm:text-3xl font-display font-bold text-green-600 dark:text-green-400" data-testid="text-safe-count">
                {analysis.safeCount}
              </div>
              <p className="text-xs text-green-700 dark:text-green-400 font-medium">Safe</p>
            </div>
            <div className="bg-red-50 dark:bg-red-900/20 rounded-xl sm:rounded-2xl p-3 sm:p-4 border border-red-200 dark:border-red-800 text-center">
              <div className="text-2xl sm:text-3xl font-display font-bold text-red-600 dark:text-red-400" data-testid="text-flagged-count">
                {analysis.flaggedCount}
              </div>
              <p className="text-xs text-red-700 dark:text-red-400 font-medium">Flagged</p>
            </div>
            <div className="bg-secondary/30 rounded-xl sm:rounded-2xl p-3 sm:p-4 border border-secondary/50 text-center">
              <div className="text-2xl sm:text-3xl font-display font-bold text-foreground" data-testid="text-total-analyzed">
                {analysis.totalAnalyzed}
              </div>
              <p className="text-xs text-muted-foreground font-medium">Total</p>
            </div>
          </div>

          <div className={cn("rounded-xl sm:rounded-2xl p-4 sm:p-5 border", overstimStyle.bg, overstimStyle.border)}>
            <div className="flex items-center gap-3 mb-2">
              <div className={cn(
                "w-10 h-10 rounded-xl flex items-center justify-center",
                overstimRating === "low" ? "bg-green-200 dark:bg-green-800/50" :
                overstimRating === "moderate" ? "bg-amber-200 dark:bg-amber-800/50" :
                "bg-red-200 dark:bg-red-800/50"
              )}>
                <Zap className={cn("w-5 h-5", overstimStyle.text)} />
              </div>
              <div>
                <h3 className="text-sm sm:text-base font-semibold">Channel Overstimulation Level</h3>
                <Badge className={cn("text-xs uppercase font-bold", overstimStyle.bg, overstimStyle.text)} data-testid="badge-channel-overstim">
                  {overstimRating}
                </Badge>
              </div>
            </div>
          </div>

          {concerns && concerns.length > 0 && (
            <div className="bg-card border rounded-xl sm:rounded-2xl p-4 sm:p-5 shadow-sm">
              <h3 className="text-xs sm:text-sm font-semibold uppercase tracking-wider text-muted-foreground mb-2 sm:mb-3 flex items-center gap-2">
                <AlertTriangle className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
                Top Concerns
              </h3>
              <ul className="space-y-2" data-testid="list-concerns">
                {concerns.map((concern, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-foreground">
                    <span className="w-5 h-5 rounded-full bg-amber-100 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400 flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5">
                      {i + 1}
                    </span>
                    {concern}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {breakdown && breakdown.length > 0 && (
            <div className="bg-card border rounded-xl sm:rounded-2xl p-4 sm:p-5 shadow-sm">
              <h3 className="text-xs sm:text-sm font-semibold uppercase tracking-wider text-muted-foreground mb-3 flex items-center gap-2">
                <Info className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
                Video Breakdown
              </h3>
              <div className="space-y-2" data-testid="list-video-breakdown">
                {breakdown.map((video, i) => (
                  <div key={i} className="flex items-center gap-3 p-2.5 sm:p-3 rounded-lg bg-secondary/30 border border-secondary/50">
                    <div className="flex-shrink-0">
                      {video.isAppropriate ? (
                        <CheckCircle className="w-4 h-4 sm:w-5 sm:h-5 text-green-500" />
                      ) : (
                        <XCircle className="w-4 h-4 sm:w-5 sm:h-5 text-red-500" />
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-xs sm:text-sm font-medium text-foreground truncate">{video.title}</p>
                      <div className="flex items-center gap-2 mt-0.5 flex-wrap">
                        <span className="text-xs text-muted-foreground">{video.ageRating}</span>
                        <span className="text-xs text-muted-foreground">{video.confidenceScore}%</span>
                        <Badge variant="outline" className="text-[10px] px-1.5 py-0">
                          {video.overstimulationRating}
                        </Badge>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className={cn(
            "rounded-xl sm:rounded-2xl p-4 sm:p-5 border-2 text-center",
            isSafe
              ? "bg-green-50 dark:bg-green-900/20 border-green-300 dark:border-green-700"
              : "bg-red-50 dark:bg-red-900/20 border-red-300 dark:border-red-700"
          )} data-testid="container-whitelist-recommendation">
            <div className={cn(
              "text-lg sm:text-xl font-display font-bold mb-1",
              isSafe ? "text-green-700 dark:text-green-400" : "text-red-700 dark:text-red-400"
            )}>
              {isSafe ? "Safe to Whitelist" : "Not Recommended for Whitelisting"}
            </div>
            <p className="text-xs sm:text-sm text-muted-foreground">
              {isSafe
                ? "Based on our analysis, this channel consistently produces age-appropriate content."
                : "This channel has content that may not be suitable for children. We recommend reviewing individual videos."}
            </p>
          </div>

          <div className="bg-gradient-to-r from-secondary/40 to-secondary/20 rounded-xl p-4 sm:p-5 border border-secondary/50">
            <p className="text-xs sm:text-sm text-muted-foreground leading-relaxed">
              <strong className="text-foreground">Important:</strong> This report is based on AI analysis of {analysis.totalAnalyzed} recent videos.
              Channel content may change over time. We recommend periodic re-evaluation and always using your own judgment.
            </p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
